import { CommonModule } from '@angular/common';
import { Component, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { BusResponse, BusType, CreateBusRequest, OperatorApiService } from '../../../core/api';
import { formatApiError } from '../../../core/utils/api-error.util';
import { ToastService } from '../../../core/utils/toast.service';

interface SeatCell {
  seatNumber: string;
  column: number;
}

@Component({
  selector: 'app-operator-buses-page',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <section class="page">
      <header class="topbar">
        <div>
          <span class="eyebrow">Manage Buses</span>
          <h1>Your Fleet</h1>
          <p>Bus layout and seat structure are generated by the backend.</p>
        </div>

        <button class="primary" type="button" (click)="toggleForm()">
          {{ showForm() ? 'Close' : '+ Add Bus' }}
        </button>
      </header>

      @if (showForm()) {
        <section class="form-card">
          <h3>Add New Bus</h3>

          <label>
            <span>Total Seats</span>
            <input type="number" min="1" max="100" [(ngModel)]="form.totalSeats" />
          </label>

          <label>
            <span>Registration Number</span>
            <input type="text" [(ngModel)]="form.registrationNumber" placeholder="DL12345" />
          </label>

          <label>
            <span>Company</span>
            <input type="text" [(ngModel)]="form.company" placeholder="Sharma Travels" />
          </label>

          <label>
            <span>Bus Type</span>
            <select [(ngModel)]="form.type">
              @for (option of busTypes; track option) {
                <option [ngValue]="option">{{ option }}</option>
              }
            </select>
          </label>

          <label class="checkbox">
            <input type="checkbox" [(ngModel)]="form.isActive" />
            <span>Active</span>
          </label>

          <button class="primary" type="button" (click)="addBus()" [disabled]="loading()">
            {{ loading() ? 'Adding...' : 'Add Bus' }}
          </button>
        </section>
      }

      <section class="list">
        @for (bus of buses(); track bus.busId) {
          <article class="card">
            <div class="card-head">
              <div class="identity">
                <strong>{{ bus.company || ('Bus #' + bus.busId) }}</strong>
                <span>{{ bus.registrationNumber || (bus.type || 'Bus Type Pending') }}</span>
                <small>{{ bus.totalSeats }} seats · {{ bus.createdAt | date:'short' }}</small>
              </div>

              <span class="status" [class.active]="bus.isActive" [class.disabled]="!bus.isActive">
                {{ bus.isActive ? 'Active' : 'Inactive' }}
              </span>
            </div>

            <div class="seat-layout">
              @for (row of seatRows(bus); track row.rowLabel) {
                <div class="seat-row">
                  <div class="row-label">{{ row.rowLabel }}</div>

                  <div class="row-grid">
                    @for (seat of row.left; track seat.seatNumber) {
                      <span class="seat">{{ seat.seatNumber }}</span>
                    }

                    <span class="aisle"></span>

                    @for (seat of row.right; track seat.seatNumber) {
                      <span class="seat">{{ seat.seatNumber }}</span>
                    }
                  </div>
                </div>
              }
            </div>
          </article>
        } @empty {
          <div class="empty">No buses added yet.</div>
        }
      </section>
    </section>
  `,
  styles: [`
    .page { display: grid; gap: 20px; color: #e2e8f0; }
    .topbar {
      display: flex;
      justify-content: space-between;
      align-items: start;
      gap: 16px;
    }
    .eyebrow {
      display: inline-block;
      margin-bottom: 6px;
      color: #93c5fd;
      font-size: 0.82rem;
      font-weight: 800;
      text-transform: uppercase;
      letter-spacing: 0.08em;
    }
    h1, h3, p { margin: 0; }
    p { color: #94a3b8; }
    .primary {
      padding: 10px 16px;
      border-radius: 12px;
      border: none;
      background: linear-gradient(135deg, #3b82f6, #2563eb);
      color: white;
      cursor: pointer;
      font: inherit;
      font-weight: 700;
    }
    .form-card, .card {
      padding: 20px;
      border-radius: 18px;
      background: #020617;
      border: 1px solid rgba(148, 163, 184, 0.14);
      display: grid;
      gap: 14px;
    }
    .form-card {
      grid-template-columns: repeat(2, minmax(0, 1fr));
      align-items: end;
    }
    .form-card h3 { grid-column: 1 / -1; }
    label { display: grid; gap: 8px; }
    label span { color: #cbd5e1; font-size: 0.92rem; }
    input, select {
      min-height: 44px;
      padding: 10px 12px;
      border-radius: 10px;
      border: 1px solid rgba(148, 163, 184, 0.16);
      background: #0f172a;
      color: white;
      font: inherit;
    }
    .checkbox {
      display: flex;
      gap: 10px;
      align-items: center;
      min-height: 44px;
    }
    .checkbox input { min-height: auto; width: 16px; height: 16px; padding: 0; }
    .checkbox span { margin: 0; }
    .list { display: grid; gap: 14px; }
    .card-head {
      display: flex;
      justify-content: space-between;
      align-items: start;
      gap: 12px;
    }
    .identity {
      display: grid;
      gap: 4px;
    }
    .identity span, .identity small { color: #94a3b8; }
    .status {
      padding: 6px 12px;
      border-radius: 999px;
      font-weight: 700;
      white-space: nowrap;
    }
    .status.active {
      background: rgba(34,197,94,0.2);
      color: #86efac;
    }
    .status.disabled {
      background: rgba(239,68,68,0.2);
      color: #fca5a5;
    }
    .seat-layout {
      display: grid;
      gap: 10px;
      padding: 14px;
      border-radius: 16px;
      background: #0b1220;
    }
    .seat-row {
      display: grid;
      grid-template-columns: 28px 1fr;
      gap: 12px;
      align-items: center;
    }
    .row-label {
      color: #7dd3fc;
      font-weight: 800;
      text-align: center;
    }
    .row-grid {
      display: grid;
      grid-template-columns: repeat(2, minmax(44px, 56px)) 28px repeat(2, minmax(44px, 56px));
      gap: 10px;
      align-items: center;
    }
    .seat {
      min-height: 40px;
      border-radius: 10px;
      display: inline-flex;
      align-items: center;
      justify-content: center;
      background: rgba(59, 130, 246, 0.16);
      border: 1px solid rgba(96, 165, 250, 0.24);
      color: #dbeafe;
      font-weight: 700;
    }
    .aisle {
      min-height: 40px;
      display: block;
    }
    .empty {
      text-align: center;
      color: #94a3b8;
      padding: 20px;
      border-radius: 16px;
      background: #020617;
    }
    @media (max-width: 860px) {
      .topbar, .card-head { flex-direction: column; }
      .form-card { grid-template-columns: 1fr; }
    }
    @media (max-width: 520px) {
      .seat-row { grid-template-columns: 1fr; }
      .row-label { text-align: left; }
      .row-grid { grid-template-columns: repeat(2, minmax(44px, 1fr)) 20px repeat(2, minmax(44px, 1fr)); }
    }
  `]
})
export class OperatorBusesPageComponent {
  private readonly api = inject(OperatorApiService);
  private readonly toast = inject(ToastService);

  readonly buses = signal<BusResponse[]>([]);
  readonly showForm = signal(false);
  readonly loading = signal(false);
  readonly busTypes: BusType[] = ['ACSeater', 'ACSleeper', 'NonACSeater', 'NonACSleeper'];

  form: CreateBusRequest = this.createEmptyForm();

  ngOnInit(): void {
    this.loadBuses();
  }

  toggleForm(): void {
    this.showForm.set(!this.showForm());
  }

  loadBuses(): void {
    this.api.listBuses().subscribe({
      next: res => this.buses.set(res),
      error: err => this.toast.error(formatApiError(err, 'Failed to load buses'))
    });
  }

  addBus(): void {
    if (!this.form.totalSeats || this.form.totalSeats < 1) {
      this.toast.error('Total seats required');
      return;
    }

    if (!this.form.registrationNumber?.trim()) {
      this.toast.error('Registration number is required');
      return;
    }

    if (!this.form.company?.trim()) {
      this.toast.error('Company is required');
      return;
    }

    this.loading.set(true);

    this.api.createBus({
      totalSeats: this.form.totalSeats,
      registrationNumber: this.form.registrationNumber.trim(),
      company: this.form.company.trim(),
      type: this.form.type,
      isActive: this.form.isActive
    }).subscribe({
      next: () => {
        this.toast.success('Bus added successfully');
        this.loading.set(false);
        this.showForm.set(false);
        this.form = this.createEmptyForm();
        this.loadBuses();
      },
      error: err => {
        this.loading.set(false);
        this.toast.error(formatApiError(err, 'Failed to add bus'));
      }
    });
  }

  seatRows(bus: BusResponse): Array<{ rowLabel: string; left: SeatCell[]; right: SeatCell[] }> {
    const grouped = new Map<string, SeatCell[]>();

    for (const seatNumber of bus.seats || []) {
      const parsed = this.parseSeatNumber(seatNumber);
      if (!parsed) {
        continue;
      }

      const current = grouped.get(parsed.rowLabel) ?? [];
      current.push({ seatNumber, column: parsed.column });
      grouped.set(parsed.rowLabel, current);
    }

    return [...grouped.entries()]
      .sort(([a], [b]) => a.localeCompare(b))
      .map(([rowLabel, seats]) => {
        const ordered = seats.sort((a, b) => a.column - b.column);
        const middle = Math.ceil(ordered.length / 2);

        return {
          rowLabel,
          left: ordered.slice(0, middle),
          right: ordered.slice(middle)
        };
      });
  }

  private parseSeatNumber(seatNumber: string): { rowLabel: string; column: number } | null {
    const match = /^([A-Za-z]+)(\d+)$/.exec(seatNumber.trim());
    if (!match) {
      return null;
    }

    return {
      rowLabel: match[1].toUpperCase(),
      column: Number(match[2])
    };
  }

  private createEmptyForm(): CreateBusRequest {
    return {
      totalSeats: 40,
      registrationNumber: '',
      company: '',
      type: 'ACSleeper',
      isActive: true
    };
  }
}
